import type { SpineEntry } from "./spine-types"

export const SAMPLE_ENTRIES: SpineEntry[] = [
  {
    id: "sample-01",
    index: 1,
    elapsed: "+1.2s",
    timestamp: "10:12:41",
    actor: "you",
    kind: "ask",
    label: "user",
    glyph: "\u25C6",
    summary: "implement a scroll command for the TUI",
  },
  {
    id: "sample-04",
    index: 2,
    elapsed: "+7.2s",
    timestamp: "10:12:48",
    actor: "arcana",
    kind: "plan",
    label: "plan",
    glyph: "\u251C",
    summary: "I will add a new ScrollCommand struct and wire it into the command registry.",
  },
  {
    id: "sample-05",
    index: 3,
    elapsed: "+12.1s",
    timestamp: "10:12:53",
    actor: "arcana",
    kind: "patch",
    label: "patch",
    glyph: "\u251C",
    summary: "scroll command implementation",
    diff: {
      files: "src/command/scroll.rs",
      stats: "+1 -1",
      body: [
        "diff --git a/src/command/scroll.rs b/src/command/scroll.rs",
        "--- a/src/command/scroll.rs",
        "+++ b/src/command/scroll.rs",
        "@@ -1,3 +1,3 @@",
        " pub struct ScrollCommand {",
        "-    pub direction: String,",
        "+    pub direction: Direction,",
        " }",
      ].join("\n"),
    },
    receipt: {
      label: "patch",
      stats: { added: 45, removed: 12 },
      status: "ok",
      files: [
        { path: "src/command/scroll.rs", added: 45, removed: 12 },
        { path: "src/command/mod.rs", added: 8, removed: 2 },
        { path: "docs/scroll-command.md", added: 18, removed: 0 },
      ],
    },
  },
  {
    id: "sample-06",
    index: 4,
    elapsed: "+13.8s",
    timestamp: "10:12:55",
    actor: "arcana",
    kind: "run",
    glyph: "\u25B7",
    summary: "cargo test --workspace",
    receipt: {
      label: "test",
      command: "cargo test --workspace",
      stats: { passed: 122, failed: 0, ignored: 0, duration: "4.12s" },
      status: "ok",
    },
  },
  {
    id: "sample-07",
    index: 5,
    elapsed: "+0.9s",
    timestamp: "10:13:00",
    kind: "fail",
    glyph: "\u00D7",
    summary: "error[E0308]: mismatched types",
    receipt: {
      label: "error",
      command: "expected `Direction`, found `i32`",
      status: "fail",
    },
  },
  {
    id: "sample-08",
    index: 6,
    elapsed: "+2.3s",
    timestamp: "10:13:02",
    actor: "arcana",
    kind: "fix",
    glyph: "\u251C",
    summary: "fix type mismatch in Direction import",
    receipt: {
      label: "fix",
      stats: { added: 3, removed: 1 },
      status: "ok",
    },
  },
  {
    id: "sample-10",
    index: 7,
    elapsed: "+1.0s",
    timestamp: "10:13:08",
    actor: "arcana",
    kind: "ok",
    glyph: "\u25CE",
    summary: "The scroll command is complete. Settled via split diff + test verification.",
  },
]