import type { SpineEntry } from "./spine-types"

export const SAMPLE_ENTRIES: SpineEntry[] = [
  {
    id: "sample-01",
    index: 1,
    elapsed: "1.2s",
    kind: "ask",
    glyph: "◆",
    summary: "implement a scroll command for the TUI",
  },
  {
    id: "sample-02",
    index: 2,
    elapsed: "3.4s",
    kind: "plan",
    glyph: "├",
    summary:
      "I will add a new ScrollCommand struct and wire it into the command registry.",
  },
  {
    id: "sample-03",
    index: 3,
    elapsed: "5.1s",
    kind: "patch",
    glyph: "├",
    summary: "src/command/scroll.rs (+45 -12)",
    diff: {
      files: "src/command/scroll.rs",
      stats: "+45 -12",
      body: [
        "--- a/src/command/scroll.rs",
        "+++ b/src/command/scroll.rs",
        "@@ -1,15 +1,48 @@",
        " pub struct ScrollCommand {",
        "-    pub direction: String,",
        "+    pub direction: Direction,",
        " }",
        "",
        "-fn scroll_old() {",
        "-    // legacy impl",
        "+impl Command for ScrollCommand {",
        "+    fn execute(&self) -> Result<()> {",
        "+        let dir = self.direction;",
        "+        scroll_viewport(dir)?;",
        "+        Ok(())",
        "+    }",
        " }",
      ].join("\n"),
      splitBody: {
        left: [
          " pub struct ScrollCommand {",
          "-    pub direction: String,",
          "+    pub direction: Direction,",
          " }",
          "",
          "-fn scroll_old() {",
          "+impl Command for ScrollCommand {",
          "+    fn execute(&self) -> Result<()> {",
        ].join("\n"),
        right: [
          " pub struct ScrollCommand {",
          "-    pub direction: String,",
          "+    pub direction: Direction,",
          " }",
          "",
          "-fn scroll_old() {",
          "+impl Command for ScrollCommand {",
          "+    fn execute(&self) -> Result<()> {",
        ].join("\n"),
      },
    },
    receipt: {
      label: "patch",
      stats: { added: 45, removed: 12 },
      status: "ok",
    },
  },
  {
    id: "sample-04",
    index: 4,
    elapsed: "6.8s",
    kind: "run",
    glyph: "▷",
    summary: "cargo test --workspace",
    receipt: {
      label: "test",
      command: "cargo test --workspace",
      stats: { passed: 122, failed: 0, ignored: 0, duration: "4.12s" },
      status: "ok",
    },
  },
  {
    id: "sample-05",
    index: 5,
    elapsed: "0.9s",
    kind: "fail",
    glyph: "×",
    summary: "error[E0308]: mismatched types",
    receipt: {
      label: "error",
      command: "expected `Direction`, found `i32`",
      status: "fail",
    },
  },
  {
    id: "sample-06",
    index: 6,
    elapsed: "2.3s",
    kind: "fix",
    glyph: "├",
    summary: "src/command/scroll.rs (+3 -1)",
    receipt: {
      label: "fix",
      stats: { added: 3, removed: 1 },
      status: "ok",
    },
  },
  {
    id: "sample-07",
    index: 7,
    elapsed: "4.1s",
    kind: "run",
    glyph: "▷",
    summary: "cargo test --workspace",
    receipt: {
      label: "test",
      command: "cargo test --workspace",
      stats: { passed: 124, failed: 0, ignored: 0, duration: "4.01s" },
      status: "ok",
    },
  },
  {
    id: "sample-08",
    index: 8,
    elapsed: "1.0s",
    kind: "ok",
    glyph: "◎",
    summary:
      "The scroll command is complete. Settled via split diff + test verification.",
  },
]
