/**
 * Phase C: Consequential Field Lineage
 *
 * Tracks the origin of values in consequential request fields.
 * Prevents prompt injection from laundering remote content through
 * model reasoning into terminal commands.
 *
 * Consequential fields:
 * - filesystem target path
 * - terminal executable
 * - terminal arguments
 * - network host
 * - network request body
 * - secret identifier
 * - MCP tool arguments
 * - delegated task text
 *
 * For UNKNOWN lineage on HIGH/CRITICAL actions: DENY or REQUIRE_APPROVAL.
 */

import type { ProvenanceLabel, SensitivityLabel, CapabilityAction } from "./types"
import type { RiskClass } from "./types"

// ─── Types ────────────────────────────────────────────────────────────

export type FieldTransformation = "DIRECT" | "MODEL_DERIVED" | "TOOL_DERIVED" | "ENCODED" | "UNKNOWN"

export interface FieldLineage {
  readonly requestField: string
  readonly sourceEventIds: ReadonlyArray<string>
  readonly provenance: ReadonlyArray<ProvenanceLabel>
  readonly sensitivity: SensitivityLabel
  readonly transformation: FieldTransformation
}

export interface LineageAssessment {
  readonly field: string
  readonly lineage: FieldLineage
  readonly risk: "SAFE" | "REQUIRES_CHECK" | "DENY"
  readonly reason?: string
}

// ─── Consequential Fields ─────────────────────────────────────────────

/**
 * Fields that carry execution authority and must have tracked lineage.
 */
export const CONSEQUENTIAL_FIELDS = [
  "resource.path",          // filesystem target path
  "executable",             // terminal executable
  "arguments",              // terminal arguments
  "networkDestination",     // network host
  "networkBody",            // network request body
  "secretIdentifier",       // secret identifier
  "mcpArguments",           // MCP tool arguments
  "delegatedTaskText",      // delegated task text
] as const

export type ConsequentialField = typeof CONSEQUENTIAL_FIELDS[number]

// ─── Lineage Classification ──────────────────────────────────────────

/**
 * Classify the lineage of a consequential field value.
 *
 * DIRECT: value came from user instruction or trusted source
 * MODEL_DERIVED: value was generated by model reasoning
 * TOOL_DERIVED: value came from a tool output
 * ENCODED: value is encoded/transformed (base64, URL encoding, etc.)
 * UNKNOWN: origin cannot be determined
 */
export function classifyFieldLineage(
  field: string,
  value: unknown,
  requestProvenance: ReadonlyArray<ProvenanceLabel>,
  requestSensitivity: ReadonlyArray<SensitivityLabel>,
): FieldLineage {
  // Determine transformation type based on provenance
  let transformation: FieldTransformation = "UNKNOWN"
  const provenance: ProvenanceLabel[] = [...requestProvenance]

  if (requestProvenance.includes("USER_INSTRUCTION")) {
    transformation = "DIRECT"
  } else if (requestProvenance.includes("MODEL_OUTPUT")) {
    transformation = "MODEL_DERIVED"
  } else if (requestProvenance.includes("TOOL_OUTPUT") || requestProvenance.includes("MCP_DESCRIPTION")) {
    transformation = "TOOL_DERIVED"
  } else if (requestProvenance.includes("REMOTE_CONTENT")) {
    transformation = "MODEL_DERIVED" // Model processed remote content
  }

  // Check for encoding transformations
  if (typeof value === "string") {
    if (isBase64(value) || isUrlEncoded(value)) {
      transformation = "ENCODED"
    }
  }

  // Determine sensitivity
  const sensitivity: SensitivityLabel = requestSensitivity.includes("SECRET")
    ? "SECRET"
    : requestSensitivity.includes("PRIVATE")
      ? "PRIVATE"
      : "PUBLIC"

  return {
    requestField: field,
    sourceEventIds: [], // Would be populated from event chain
    provenance,
    sensitivity,
    transformation,
  }
}

/**
 * Assess whether a field lineage is safe for the given action risk.
 *
 * SAFE: lineage is DIRECT or trusted
 * REQUIRES_CHECK: lineage is MODEL_DERIVED on HIGH/CRITICAL action
 * DENY: lineage is UNKNOWN on HIGH/CRITICAL action, or SECRET in ENCODED
 */
export function assessFieldLineage(
  lineage: FieldLineage,
  action: CapabilityAction,
  risk: RiskClass,
): LineageAssessment {
  // SECRET in ENCODED form is a potential exfiltration vector
  if (lineage.sensitivity === "SECRET" && lineage.transformation === "ENCODED") {
    return {
      field: lineage.requestField,
      lineage,
      risk: "DENY",
      reason: "SECRET value in encoded form — potential exfiltration",
    }
  }

  // UNKNOWN lineage on HIGH/CRITICAL actions
  if (lineage.transformation === "UNKNOWN" && (risk === "HIGH" || risk === "CRITICAL")) {
    return {
      field: lineage.requestField,
      lineage,
      risk: "DENY",
      reason: `UNKNOWN lineage on ${risk} action`,
    }
  }

  // REMOTE_CONTENT on consequential write/execute actions
  if (
    lineage.provenance.includes("REMOTE_CONTENT") &&
    (action === "process.execute" || action === "filesystem.write" || action === "network.write")
  ) {
    return {
      field: lineage.requestField,
      lineage,
      risk: "REQUIRES_CHECK",
      reason: "REMOTE_CONTENT in consequential field — requires intent binding",
    }
  }

  // MCP_DESCRIPTION on secret/process actions
  if (
    lineage.provenance.includes("MCP_DESCRIPTION") &&
    (action === "secret.use" || action === "process.execute")
  ) {
    return {
      field: lineage.requestField,
      lineage,
      risk: "DENY",
      reason: "MCP_DESCRIPTION cannot authorize secret or process execution",
    }
  }

  return {
    field: lineage.requestField,
    lineage,
    risk: "SAFE",
  }
}

/**
 * Assess all consequential fields in a request.
 * Returns the worst risk assessment across all fields.
 */
export function assessRequestLineage(
  fields: Record<string, unknown>,
  requestProvenance: ReadonlyArray<ProvenanceLabel>,
  requestSensitivity: ReadonlyArray<SensitivityLabel>,
  action: CapabilityAction,
  risk: RiskClass,
): { overall: "SAFE" | "REQUIRES_CHECK" | "DENY"; assessments: LineageAssessment[] } {
  const assessments: LineageAssessment[] = []
  let worst: "SAFE" | "REQUIRES_CHECK" | "DENY" = "SAFE"

  for (const field of CONSEQUENTIAL_FIELDS) {
    const value = fields[field]
    if (value === undefined) continue

    const lineage = classifyFieldLineage(field, value, requestProvenance, requestSensitivity)
    const assessment = assessFieldLineage(lineage, action, risk)
    assessments.push(assessment)

    if (assessment.risk === "DENY") worst = "DENY"
    else if (assessment.risk === "REQUIRES_CHECK" && worst !== "DENY") worst = "REQUIRES_CHECK"
  }

  return { overall: worst, assessments }
}

// ─── Encoding Detection ──────────────────────────────────────────────

function isBase64(value: string): boolean {
  // Simple heuristic: base64 strings are long, alphanumeric + /+=, and padded
  if (value.length < 8) return false
  return /^[A-Za-z0-9+/]+=*$/.test(value) && value.length % 4 === 0
}

function isUrlEncoded(value: string): boolean {
  // URL-encoded strings contain % followed by hex digits
  return /%[0-9A-Fa-f]{2}/.test(value)
}
